title: KinGUII
tagline: "Kinetic Evaluations with a Graphical User Interface"
theme: "0c"
reverse: True
description: >
  KinGUII makes it easy to create, customize and evaluate kinetic models.

url: "http://zhenglei-gao.github.io/Test"
author:
  name: "Zhenglei Gao"
  github: "zhenglei-gao/Test"

sidebar:
  - {item: NEWS, href: 'Test/blog', icon: 'bullhorn'}
  - {item: Manual, href: 'Test/publications', icon: 'hand-o-right'}
  - {item: Example Projects, href: 'Test/projects', icon: 'puzzle-piece'}
  - {item: About KinGUII, href: 'Test/software', icon: 'info-circle'}
  - {item: Development, href: 'Test/research', icon: 'cogs'}


projects:
  - {title: "Visualizing Bike Sharing Networks", 
     url: "http://slidify.github.io/dcmeetup/demo/bikeshare",
     thumbnail: 'citibikes.png'
    }
  - {title: "Animated Choropleths",
     url: "http://rmaps.github.io/blog/posts/animated-choropleths/index.html",
     thumbnail: "animated-choropleths.png"
    }
  - {title: Visualizing Medal Tally at Sochi,
  	 url: "http://ramnathv.ocpu.io/sochi/www/",
  	 thumbnail: "sochi.png"
  	}
  - {title: Online Playground for rCharts,
     url: "http://rcharts.io/playground",
     thumbnail: "rcharts.png"
    }
  - {title: 100 Centuries of Sachin Tendulkar,
  	 url: 'http://ramnathv.github.io/sachin100s/',
  	 thumbnail: 'sachin.png'
    }
  - {title: Interactive Controls with rCharts,
     url: 'http://rcharts.io/icontrols',
     thumbnail: 'icontrols.png'
    }
